name: Create Resource Pack

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '!')"
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: create zip file
      uses: vimtor/action-zip@v1
      with:
        files: /moba_resource_pack
        dest: moba_rp.zip
    - name: setting up some variables
      id: vars
      shell: bash
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: v${{ steps.vars.outputs.sha_short }}
        release_name: Server RP ${{ steps.vars.outputs.sha_short }}
        body: |
          The latest resource pack for my server
        draft: false
        prerelease: false
    - name: upload artifact
      env:
        GITHUB_TOKEN: ${{ github.token }}
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{github.workspace}}/moba_rp.zip
        asset_name: moba_rp.zip
        asset_content_type: application/zip
    

    
  