name: Create Resource Pack

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: create zip file
      uses: vimtor/action-zip@v1
      with:
        files: /moba_resource_pack
        dest: moba_rp.zip
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: moba_rp.zip