name: Create Resource Pack

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: create zip file
      uses: vimtor/action-zip@v1
      with:
        files: /moba_resource_pack
        dest: moba_rp.zip
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: moba_rp.zip
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          The latest resource pack for my server
        draft: false
        prerelease: false

    
  