name: Create Resource Pack

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: create zip file
      uses: vimtor/action-zip@v1
      with:
        files: /moba_resource_pack
        dest: moba_rp.zip
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: ${{ github.workspace }}/moba_rp.zip
  release:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@master
    - name: Create release
      uses: Roang-zero1/github-create-release-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create GitHub release
      uses: Roang-zero1/github-upload-release-artifacts-action@master
      with:
        args:
        - ${{ github.workspace }}/moba_rp.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
